"""update table rag

Revision ID: 0f65ed67534d
Revises: 50ac4a7ec1ad
Create Date: 2026-01-15 06:40:05.233202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f65ed67534d'
down_revision: Union[str, None] = '50ac4a7ec1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_benchmark_results', sa.Column('mrr_score', sa.Float(), nullable=True))
    op.add_column('rag_benchmark_results', sa.Column('retrieved_ids', sa.JSON(), nullable=True))
    op.drop_column('rag_benchmark_results', 'bleu_score')
    op.add_column('rag_test_cases', sa.Column('target_article_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_test_cases', 'target_article_id')
    op.add_column('rag_benchmark_results', sa.Column('bleu_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('rag_benchmark_results', 'retrieved_ids')
    op.drop_column('rag_benchmark_results', 'mrr_score')
    # ### end Alembic commands ###
