"""update model agar support  auto-ingest

Revision ID: 1e7e33286032
Revises: 8d81aa719684
Create Date: 2025-12-22 14:24:58.903976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7e33286032'
down_revision: Union[str, None] = '8d81aa719684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_ingested', sa.Boolean(), nullable=True))
    op.add_column('articles', sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'ingested_at')
    op.drop_column('articles', 'is_ingested')
    # ### end Alembic commands ###
