"""tambah quranatined tabel

Revision ID: 2c29cd28aa35
Revises: b3d25c9fd792
Create Date: 2026-01-11 23:27:04.027485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c29cd28aa35'
down_revision: Union[str, None] = 'b3d25c9fd792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarantined_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_target_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('quarantined_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quarantined_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quarantined_items')
    # ### end Alembic commands ###
