"""update message model menambahkan isdelivered untuk centang 2

Revision ID: 38fc37a850ec
Revises: 635c575fdf46
Create Date: 2026-01-18 12:56:37.556877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38fc37a850ec'
down_revision: Union[str, None] = '635c575fdf46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_delivered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_delivered')
    # ### end Alembic commands ###
