"""update model chat

Revision ID: 3d75bb63d1b2
Revises: 363082d5666c
Create Date: 2025-12-20 20:07:03.265276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d75bb63d1b2'
down_revision: Union[str, None] = '363082d5666c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_participants', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('chat_participants', sa.Column('unread_count', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('is_group', sa.Boolean(), nullable=True))
    op.add_column('chats', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('chats', sa.Column('image_url', sa.String(length=1024), nullable=True))
    op.add_column('chats', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('chats', sa.Column('last_message_text', sa.Text(), nullable=True))
    op.add_column('chats', sa.Column('last_message_time', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'chats', 'users', ['created_by'], ['id'])
    op.add_column('messages', sa.Column('type', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('attachment_url', sa.String(length=1024), nullable=True))
    op.add_column('messages', sa.Column('is_read_by_all', sa.Boolean(), nullable=True))
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('messages', 'is_read_by_all')
    op.drop_column('messages', 'attachment_url')
    op.drop_column('messages', 'type')
    op.drop_constraint(None, 'chats', type_='foreignkey') # type: ignore
    op.drop_column('chats', 'last_message_time')
    op.drop_column('chats', 'last_message_text')
    op.drop_column('chats', 'created_by')
    op.drop_column('chats', 'image_url')
    op.drop_column('chats', 'name')
    op.drop_column('chats', 'is_group')
    op.drop_column('chat_participants', 'unread_count')
    op.drop_column('chat_participants', 'is_admin')
    # ### end Alembic commands ###
