"""update: menambahkan professional tabel 

Revision ID: 4c8efd87e5b3
Revises: a168dc2b17b4
Create Date: 2026-01-06 16:38:03.289122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8efd87e5b3'
down_revision: Union[str, None] = 'a168dc2b17b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('pro_type', sa.String(length=50), nullable=True),
    sa.Column('full_name_with_title', sa.String(length=255), nullable=True),
    sa.Column('str_number', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('practice_address', sa.Text(), nullable=True),
    sa.Column('practice_schedule', sa.Text(), nullable=True),
    sa.Column('str_image_path', sa.String(length=1024), nullable=True),
    sa.Column('ktp_image_path', sa.String(length=1024), nullable=True),
    sa.Column('selfie_image_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('str_number'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professional_profiles')
    # ### end Alembic commands ###
