"""add index to source url => article

Revision ID: 5685abdd21be
Revises: d0077ad9b147
Create Date: 2025-12-10 16:59:31.290195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5685abdd21be'
down_revision: Union[str, None] = 'd0077ad9b147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_articles_source_url'), 'articles', ['source_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_source_url'), table_name='articles')
    # ### end Alembic commands ###
