"""tambah view kolom di article

Revision ID: 6ded8e98d4ac
Revises: c1c41494219a
Create Date: 2026-01-10 11:27:33.825744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ded8e98d4ac'
down_revision: Union[str, None] = 'c1c41494219a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'views')
    # ### end Alembic commands ###
