"""add otp to user

Revision ID: 8d81aa719684
Revises: 04a7e20d0ba2
Create Date: 2025-12-22 04:54:39.047308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d81aa719684'
down_revision: Union[str, None] = '04a7e20d0ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expires')
    op.drop_column('users', 'reset_otp')
    # ### end Alembic commands ###
