"""add google login columns

Revision ID: 972b88758622
Revises: 0781525ab1ea
Create Date: 2025-12-02 19:09:13.757866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972b88758622'
down_revision: Union[str, None] = '0781525ab1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_uid', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_uid'])
    op.execute("UPDATE users SET auth_provider = 'email' WHERE auth_provider IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_uid')
    # ### end Alembic commands ###
