"""update tabel chat participant untuk soft delete 

Revision ID: a168dc2b17b4
Revises: ce0868a1294c
Create Date: 2026-01-05 06:33:26.889048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a168dc2b17b4'
down_revision: Union[str, None] = 'ce0868a1294c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_participants', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_participants', 'is_hidden')
    # ### end Alembic commands ###
