"""update tabel appeal

Revision ID: b3d25c9fd792
Revises: 6ded8e98d4ac
Create Date: 2026-01-11 08:25:17.152231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d25c9fd792'
down_revision: Union[str, None] = '6ded8e98d4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeals', sa.Column('justification', sa.Text(), nullable=True))
    op.add_column('appeals', sa.Column('admin_note', sa.Text(), nullable=True))
    op.add_column('appeals', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appeals', 'reviewed_at')
    op.drop_column('appeals', 'admin_note')
    op.drop_column('appeals', 'justification')
    # ### end Alembic commands ###
