"""update chatbot table

Revision ID: bd80bfd261bf
Revises: 0f65ed67534d
Create Date: 2026-01-17 22:07:39.220749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd80bfd261bf'
down_revision: Union[str, None] = '0f65ed67534d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_chats', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_chats', 'title')
    # ### end Alembic commands ###
