"""update tabel chat: tambah allow member invites kolom

Revision ID: c9d594ab5961
Revises: 9d55734e7cbc
Create Date: 2026-01-01 17:52:44.910690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d594ab5961'
down_revision: Union[str, None] = '9d55734e7cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('allow_member_invites', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'allow_member_invites')
    # ### end Alembic commands ###
