"""update tabel chat: chat participant, reply, banned user 

Revision ID: ce0868a1294c
Revises: c9d594ab5961
Create Date: 2026-01-04 19:14:38.769136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0868a1294c'
down_revision: Union[str, None] = 'c9d594ab5961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_participants', sa.Column('last_cleared_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('group_banned_users', 'id')
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to_id')
    op.drop_column('messages', 'is_deleted')
    op.add_column('group_banned_users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('chat_participants', 'last_cleared_at')
    # ### end Alembic commands ###
