"""change log target_id to string

Revision ID: d0077ad9b147
Revises: f27ee9d76ee3
Create Date: 2025-12-09 13:02:44.750115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0077ad9b147'
down_revision: Union[str, None] = 'f27ee9d76ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
