"""add security pin hash

Revision ID: df809397b485
Revises: 972b88758622
Create Date: 2025-12-06 12:44:16.140254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df809397b485'
down_revision: Union[str, None] = '972b88758622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_pin_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_pin_hash')
    # ### end Alembic commands ###
