"""update user table : saved post logic

Revision ID: f7f99f3b0608
Revises: 1fde47d71d4d
Create Date: 2025-12-14 23:08:39.799280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f99f3b0608'
down_revision: Union[str, None] = '1fde47d71d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_saved_posts_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_saved_posts_public')
    # ### end Alembic commands ###
